#!/bin/bash
# {{{ Deploy a new LaTeX style or package.
#
# Usage:
#   deploy tlc-article.cls
#
# Note:
#   I use this script to test my deployment before publishing with CTAN.

main() {
  [[ $# -eq 0 ]] && { echo "Usage: $0 filename"; exit 1; }
  echo "Filename w/  extension: ${1}"
  echo "Filename w/o extension: ${1%.}"
}

# -------------------------------------------------------------------------- }}}
# {{{ Kick start start this script.

main $@

# -------------------------------------------------------------------------- }}}
