sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update 
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build GettingStarted.tex 
deploy:
  provider: releases
  api_key:
    secure: 35625aa2b42cfa72b160d975a4fa6db589c63f27
  file:
  - _build/GettingStarted.pdf
  skip_cleanup: true
  on:
    tags: true
